language: node_js
node_js:
  - '10.15.3'

sudo: false

cache: yarn

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
  - yarn
  - yarn vscode:prepublish

script:
  - yarn format
  - yarn lint
  - yarn test
